### ISSUE TITLE
Preload stream issue with 0.91

### ISSUE THREAD

**Issue by winterscar** [custom-cards/camera-card#2]
Hi,

I love this card, but I have a small issue with hass 0.91. 

As you can see in the screenshot below, the preload stream tickbox shows up all the time!
This may be a Hass issue, but I'm not sure. 

<img width="1120" alt="preload-stream" src="https://user-images.githubusercontent.com/11340175/55689426-32867480-597c-11e9-98f8-be15026223d9.png">

**Comment by iantrich** [comment]
This card is just a wrapper around the more info camera dialogue. Nothing to be done here. Hopefully we’ll have a better solution in core soon.
