### ISSUE TITLE
Feature Request: Optionally use a different camera for thumb sized stream

### ISSUE THREAD

**Issue by legomind** [custom-cards/camera-card#3]
Allow specifying a different camera for thumbnail sized stream.
This card works great, but when used with several 720p cameras bandwidth gets used very fast.

I have a lower quality camera setup in HA and would only like to view the full resolution camera once the card has been clicked.

**Comment by iantrich** [comment]
This card is what it is as far as I am concerned. It’s a hack until we have a better solution in core, hopefully soon. Thanks.
