### ISSUE TITLE
Card does not appear until the camera loads

### ISSUE THREAD

**Issue by jul1u5** [custom-cards/camera-card#4]
Currently, while the camera stream loads the card is not visible. Because of this, the layout of the UI changes multiple times on page load.

I suggest adding an option `fallback` which would take an image. This image would appear immediately and later change to a camera stream when it loads.

**Comment by iantrich** [comment]
Since the release of 0.92, picture cards now support camera streams. I recommend using the core picture cards. I'll be deprecating this.
